name: domain
description: A collection of basic types and abstract classes for TinyTree
version: 0.0.1

environment:
  sdk: ^3.10.7

# dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
